export enum MutationTypes {
  SET_CURRENT_USER = "SET_CURRENT_USER",
  SET_AUTH_LOADING = "SET_AUTH_LOADING",
  SET_AUTH_ERROR = "SET_AUTH_ERROR",
  //EVENTS
  SET_EVENT_LOADING = "SET_EVENT_LOADING",
  SET_EVENTS = "SET_EVENTS",
  SET_EVENT_ERROR = "SET_EVENT_ERROR"
}
